export const MY_ORDERS_ACTION_TYPES = {
    SET_MY_ORDERS_START: "my-orders/SET_MY_ORDERS_START",
    SET_MY_ORDERS_SUCCESS: "my-orders/SET_MY_ORDERS_SUCCESS",
    SET_MY_ORDERS_FAILED: "my-orders/SET_MY_ORDERS_FAILED",
}