export const USER_ACTION_TYPES = {
  CHECK_USER_SESSION_START: "user/CHECK_USER_SESSION_START",
  CHECK_USER_SESSION_SUCCESS: "user/CHECK_USER_SESSION_SUCCESS",
  CHECK_USER_SESSION_FAILED: "user/CHECK_USER_SESSION_FAILED",
  
  USER_SIGNOUT_START: "user/USER_SIGNOUT_START",
  USER_SIGNOUT_SUCCESS: "user/USER_SIGNOUT_SUCCESS",
  USER_SIGNOUT_FAILED: "user/USER_SIGNOUT_FAILED",

  GOOGLE_SIGN_IN_START: "user/GOOGLE_SIGN_IN_START",
  GOOGLE_SIGN_IN_SUCCESS: "user/GOOGLE_SIGN_IN_SUCCESS",
  GOOGLE_SIGN_IN_FAILED: "user/GOOGLE_SIGN_IN_FAILED",
};
