export const PRODUCT_ACTION_TYPES = {
    SET_PRODUCTS: "products/SET_PRODUCTS",
    SET_PRODUCTS_START: "products/SET_PRODUCTS_START",
    SET_PRODUCTS_SUCCESS:"products/SET_PRODUCTS_SUCCESS",
    SET_PRODUCTS_FAILED: "products/SET_PRODUCTS_FAILED"
}