export const TOP_VIEWED_ACTION_TYPES = {
  TOP_VIEWED_SUCCESS: "top-viewed/TOP_VIEWED_SUCCESS",
  TOP_VIEWED_START: "top-viewed/TOP_VIEWED_START",
  TOP_VIEWED_FAILED: "top-viewed/TOP_VIEWED_FAILED",
};
